dimple_objeq:
  jshead: 
    - js/ace.js
    - js/util.js
    - js/parser.js
    - js/objeq-parser-junqi.js
    - js/compiler.js
    - js/junqi.js
    - js/index_junqi_extensions.js
    - js/beautify.js
    - js/jquery.min.js
    - js/bootstrap.js
    - js/d3.js
    - js/dimple.v1.1.5.js
    - js/d3-grid.js
    - js/lodash.js
  css: css/bootstrap.css
  cdn:
    jshead:
      - ./js/ace.js
      - ./js/util.js
      - ./js/parser.js
      - ./js/objeq-parser-junqi.js
      - ./js/compiler.js
      - ./js/junqi.js
      - ./js/index_junqi_extensions.js
      - ./js/beautify.js
      - ./js/jquery.min.js
      - ./js/bootstrap.js
      - ./js/d3.js
      - ./js/dimple.v1.1.5.js
      - ./js/d3-grid.js
      - ./js/lodash.js
    css: ./css/bootstrap.css
